workflows:
  default-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      python: 3.10
    scripts:
      - name: Install dependencies
        script: |
          pip3 install --upgrade pip
          pip3 install flet telethon cryptography pysocks
      - name: Build Flet APK
        script: |
          # نستخدم أمر البناء مع التأكد من تحديد الملف الرئيسي
          flet build apk --project main.py
    artifacts:
      - build/apk/app-release.apk
