workflows:
  default-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      python: 3.10
    scripts:
      - name: Install Dependencies
        script: |
          pip3 install flet telethon
      - name: Build APK
        script: |
          # تأكد أن ملفك الرئيسي اسمه main.py
          flet build apk --project main.py
    artifacts:
      - build/apk/app-release.apk
